services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_PASSWORD: docker-postgres
      POSTGRES_DB: security-test
      POSTGRES_USER: security-test
    ports:
      - 5432:5432
    volumes:
      - ./volume/db:/var/lib/postgresql/data
    container_name: postgresql_security
