spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security-test
    username: security-test
    password: docker-postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false
